#! /bin/sh
# export env

# hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# java fix
wmname LG3D & 

# arandr - display settings
$HOME/.screenlayout/display.sh

# kill applets and other autostart apps
killall -q nm-applet &
killall -q blueman-applet &
killall -q firewall-applet &
killall -q volctl &
killall -q tint2 &

# nitrogen - wallpaper
nitrogen --restore &

# picom
picom --experimental-backends --config $HOME/.config/picom/picom.conf &

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# light-locker (use lightdm as screenlocker)
light-locker &

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8
done

bspc config focused_border_color '#9bdead'
bspc config active_border_color  '#e8edea'
bspc config normal_border_color  '#e8edea'

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# focus window wo der cursor gerade darüber ist
bspc config focus_follows_pointer	false

# autostart

# polybar (horizontal bar)
$HOME/.config/polybar/launch.sh

# tint2 (vertical bar)
tint2 &

# applets
nm-applet &
blueman-applet &
firewall-applet &
volctl &

# nitrogen - wallpaper
nitrogen --restore &

bspc rule -a Gimp-2.10 state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a PacketTracer state=floating
